name: AliveList
version: ${project.version}
main: com.fakedomain.alivelist.Alivelist
api-version: 1.13

commands:
  alivelist:
    description: Lists alive players, even disconnected ones
    usage: /alivelist